### ISSUE TITLE
2.6 roadmap

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#257]
+ [x] No-column print in ls and ls-remote if piping isatty stdout. #249
+ [x] Do not hide installed plugins in fisher ls-remote. #250
+ [x] Auto-complete **only** fisher [install] with ls-remote output _if_ available. #256
+ [x] ~~Use a single source of truth for the blacklisted plugins. #255~~
+ [x] Check if `git`, `curl`, etc., are installed before using them and inform the user about it. #253

**Comment by bucaran** [comment]
https://github.com/fisherman/fisherman/commit/62e5b3e6b2bf4965baf8b3a4afea1e609abc7369
